# Regenerates the sfxr corpus into a scratch directory and checks it byte-for-byte against
# the committed one.
#
# The corpus is committed because a test that compares against a moving target is not a
# test. That only holds if regenerating gives back exactly the same bytes — sfxr pulls from
# a PRNG inside its audio loop, so the waveform depends on the generator, and the reference
# substitutes a fixed one precisely so this is true on every platform. If this test ever
# fails, every comparison in the rig has silently changed meaning.
#
# Run through ctest; see tests/CMakeLists.txt.

file(REMOVE_RECURSE "${SCRATCH}")
file(MAKE_DIRECTORY "${SCRATCH}/cases" "${SCRATCH}/vectors")

execute_process(
    COMMAND "${SFXR_REF}" corpus "${SCRATCH}" --per-preset 6
    RESULT_VARIABLE generate_result
    OUTPUT_VARIABLE generate_output
    ERROR_VARIABLE generate_output
)
if(NOT generate_result EQUAL 0)
    message(FATAL_ERROR "sfxr-ref corpus failed:\n${generate_output}")
endif()

# The manifest lists what the corpus is meant to contain, so it is compared first: a
# difference here means the generator itself changed, which explains any vector that also
# differs and is the more useful thing to report.
file(READ "${CORPUS}/manifest.json" committed_manifest)
file(READ "${SCRATCH}/manifest.json" fresh_manifest)
if(NOT committed_manifest STREQUAL fresh_manifest)
    message(FATAL_ERROR
        "The regenerated manifest differs from the committed one.\n"
        "sfxr-ref no longer produces the corpus that is checked in — either the "
        "reference synthesis changed, or its substitute PRNG did. Every comparison in "
        "the rig is measured against these vectors, so this has to be understood before "
        "any result from it means anything.")
endif()

file(GLOB committed_vectors RELATIVE "${CORPUS}/vectors" "${CORPUS}/vectors/*.wav")
list(LENGTH committed_vectors committed_count)
if(committed_count EQUAL 0)
    message(FATAL_ERROR "No committed vectors found in ${CORPUS}/vectors")
endif()

set(differing "")
foreach(vector IN LISTS committed_vectors)
    file(SHA256 "${CORPUS}/vectors/${vector}" committed_hash)
    if(NOT EXISTS "${SCRATCH}/vectors/${vector}")
        list(APPEND differing "${vector} (not regenerated)")
        continue()
    endif()
    file(SHA256 "${SCRATCH}/vectors/${vector}" fresh_hash)
    if(NOT committed_hash STREQUAL fresh_hash)
        list(APPEND differing "${vector}")
    endif()
endforeach()

if(differing)
    string(REPLACE ";" "\n  " differing_text "${differing}")
    message(FATAL_ERROR
        "These vectors are not reproducible:\n  ${differing_text}")
endif()

message(STATUS "${committed_count} sfxr vectors regenerated byte-identically")
