#!/usr/bin/env node
// Builds examples/patches/break-chopper.json — the slicer's showcase, with its break —
// and examples/patches/kit-chopper.json, the hybrid: the whole 909 kit with a chopper
// riding under it, whose buffer is the one the editor's Capture button overwrites.
//
// The break is not a recording anyone owns: it is one bar of the Euclid demo's own
// groove, rendered by sg-render from a patch already in the repository, folded to mono
// and embedded as pcm16 base64. Everything about it regenerates from source, which is
// the same promise every golden vector makes — and the reason this is a script with a
// --check mode rather than a wav somebody once dragged in: generated files drift the
// moment anything upstream changes, and the suite should say so.
//
//   node tools/make-break.mjs [--check] <path-to-sg-render>

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(root, 'examples', 'patches', 'break-chopper.json');
const kitTarget = join(root, 'examples', 'patches', 'kit-chopper.json');

const args = process.argv.slice(2);
const check = args.includes('--check');
const renderer = args.find((a) => !a.startsWith('--'));
if (!renderer) {
  console.error('usage: node tools/make-break.mjs [--check] <path-to-sg-render>');
  process.exit(2);
}

// One bar of the Euclid groove at 120: exactly two seconds.
const scratch = mkdtempSync(join(tmpdir(), 'make-break-'));
// The scratch dir dies with the process — the day the comparators leaked two
// thousand of these and filled the disk to zero is not getting a sequel.
process.on('exit', () => rmSync(scratch, { recursive: true, force: true }));
const wavPath = join(scratch, 'break.wav');
execFileSync(renderer, [
  join(root, 'examples', 'patches', 'nodes', 'Euclid.json'),
  wavPath, '--seconds', '2', '--silent', '--quiet',
]);

const wav = readFileSync(wavPath);
let offset = 12;
while (wav.toString('ascii', offset, offset + 4) !== 'data') {
  offset += 8 + wav.readUInt32LE(offset + 4);
}
const dataStart = offset + 8;
const frameCount = Math.floor((wav.length - dataStart) / 4); // 16-bit stereo
const pcm = Buffer.alloc(frameCount * 2);
for (let i = 0; i < frameCount; i++) {
  // The demo renders identical channels; the left one is the mono fold.
  pcm.writeInt16LE(wav.readInt16LE(dataStart + i * 4), i * 2);
}

const node = (id, type, x, y, parameters, buffer) => ({
  id, type,
  ...(buffer ? { buffer } : {}),
  position: { x: x * 560, y: y * 360 },
  ...(parameters ? { parameters } : {}),
});
const wire = (fn, fp, tn, tp) => ({ from: { node: fn, port: fp }, to: { node: tn, port: tp } });

const patch = {
  schema_version: 3,
  metadata: {
    name: 'Break Chopper',
    description: 'One bar of the Euclid demo, chopped: a StepSequencer lane picks '
      + 'which eighth of the break each eighth-note plays. Chop knobs re-cut the '
      + 'bar while it runs; swing shuffles it; tempo re-times the cuts while each '
      + 'slice keeps its own speed, which is the old jungle trick. Generated by '
      + 'tools/make-break.mjs. Do not edit by hand.',
    tags: ['sampler', 'slicer', 'break', 'generated'],
  },
  buffers: {
    break: { sample_rate: 48000, channels: 1, format: 'pcm16', data: pcm.toString('base64') },
  },
  nodes: [
    node('clock', 'Clock', 0, 0, { bpm: 120, division: 3, swing: 0, width: 5 }),
    node('lane', 'StepSequencer', 1, 0, {
      length: 8,
      step1: 0, step2: 0.125, step3: 0.25, step4: 0.375,
      step5: 0.5, step6: 0.125, step7: 0.75, step8: 0.875,
    }),
    node('chop', 'Sampler', 2, 0, { slices: 8, level: 0.9, loop: 0 }, 'break'),
    { id: 'out', type: 'Output', host: 'stereo',
      position: { x: 3 * 560, y: 0 }, parameters: { level: 0.8, safety_limit: 1 } },
  ],
  connections: [
    wire('clock', 'gate', 'lane', 'clock'),
    wire('clock', 'bar', 'lane', 'reset'),
    wire('clock', 'gate', 'chop', 'gate'),
    wire('lane', 'out', 'chop', 'slice'),
    wire('chop', 'out', 'out', 'left'),
    wire('chop', 'out', 'out', 'right'),
  ],
  controls: [
    { id: 'tempo', label: 'Tempo', kind: 'knob',
      target: { node: 'clock', parameter: 'bpm' },
      min: 90, max: 160, default: 120, scaling: 'linear' },
    { id: 'swing', label: 'Swing', kind: 'knob',
      target: { node: 'clock', parameter: 'swing' },
      min: 0, max: 1, default: 0, scaling: 'linear' },
    { id: 'chop6', label: 'Chop 6', kind: 'knob',
      target: { node: 'lane', parameter: 'step6' },
      min: 0, max: 1, default: 0.125, scaling: 'linear' },
    { id: 'chop7', label: 'Chop 7', kind: 'knob',
      target: { node: 'lane', parameter: 'step7' },
      min: 0, max: 1, default: 0.75, scaling: 'linear' },
  ],
};

const text = `${JSON.stringify(patch, null, 2)}\n`;

// The hybrid: the 909 kit verbatim, plus a chopper cluster aimed at a buffer named
// "capture" — the name the editor's Capture button writes. It ships pre-loaded with
// the same Euclid bar so it makes sound out of the box; the first Capture replaces
// that with whatever is drawn on the kit's own roll.
const kit = JSON.parse(readFileSync(join(root, 'examples', 'patches', 'drums909', 'kit.json'), 'utf8'));
kit.schema_version = 3;
kit.metadata.name = 'Kit Chopper';
kit.metadata.description = 'The 909 kit with a chopper underneath: draw drums on the '
  + 'roll, press Capture, and the Sampler starts chopping the bar you drew. Until '
  + 'then it chops a bar of the Euclid groove. Generated by tools/make-break.mjs. '
  + 'Do not edit by hand.';
kit.metadata.tags = ['drums', 'sampler', 'slicer', 'capture', 'generated'];
kit.buffers = {
  capture: { sample_rate: 48000, channels: 1, format: 'pcm16', data: pcm.toString('base64') },
};
const kitBottom = 7200;
kit.nodes.push(
  node('chopclock', 'Clock', 0, 0, { bpm: 128, division: 3, swing: 0, width: 5 }),
  node('choplane', 'StepSequencer', 1, 0, {
    length: 8,
    step1: 0, step2: 0.125, step3: 0.25, step4: 0.375,
    step5: 0.5, step6: 0.125, step7: 0.75, step8: 0.875,
  }),
  node('chop', 'Sampler', 2, 0, { slices: 8, level: 0.6, loop: 0 }, 'capture'),
);
for (const id of ['chopclock', 'choplane', 'chop']) {
  const added = kit.nodes.find((n) => n.id === id);
  added.position.y += kitBottom;
}
kit.connections.push(
  wire('chopclock', 'gate', 'choplane', 'clock'),
  wire('chopclock', 'bar', 'choplane', 'reset'),
  wire('chopclock', 'gate', 'chop', 'gate'),
  wire('choplane', 'out', 'chop', 'slice'),
  wire('chop', 'out', 'out', 'left'),
  wire('chop', 'out', 'out', 'right'),
);
kit.controls.push(
  { id: 'chop_swing', label: 'Chop Swing', kind: 'knob',
    target: { node: 'chopclock', parameter: 'swing' },
    min: 0, max: 1, default: 0, scaling: 'linear' },
  { id: 'chop6', label: 'Chop 6', kind: 'knob',
    target: { node: 'choplane', parameter: 'step6' },
    min: 0, max: 1, default: 0.125, scaling: 'linear' },
  { id: 'chop7', label: 'Chop 7', kind: 'knob',
    target: { node: 'choplane', parameter: 'step7' },
    min: 0, max: 1, default: 0.75, scaling: 'linear' },
  { id: 'chop_level', label: 'Chop Level', kind: 'knob',
    target: { node: 'chop', parameter: 'level' },
    min: 0, max: 1, default: 0.6, scaling: 'linear' },
);
const kitText = `${JSON.stringify(kit, null, 2)}\n`;

if (check) {
  let stale = false;
  if (readFileSync(target, 'utf8') !== text) {
    console.error('stale: examples/patches/break-chopper.json');
    stale = true;
  }
  if (readFileSync(kitTarget, 'utf8') !== kitText) {
    console.error('stale: examples/patches/kit-chopper.json');
    stale = true;
  }
  if (stale) {
    console.error('Run: node tools/make-break.mjs ' + renderer);
    process.exit(1);
  }
  console.log('break-chopper.json and kit-chopper.json match their sources.');
} else {
  writeFileSync(target, text);
  writeFileSync(kitTarget, kitText);
  console.log('break-chopper.json and kit-chopper.json written, '
    + `${frameCount} frames of break embedded in each.`);
}
