#!/usr/bin/env python
"""Regenerates dsp-core/src/sine_table.h. The values are fixed by mathematics; this
exists so the recipe outlives whoever ran it, per the generated-file discipline."""
import math, io, struct

N = 4096
def f32(x):
    return struct.unpack('<f', struct.pack('<f', x))[0]
values = [f32(math.sin(2.0 * math.pi * i / N)) for i in range(N + 1)]
lines = []
for i in range(0, N + 1, 4):
    def lit(v):
        t = '%.9g' % v
        if '.' not in t and 'e' not in t and 'inf' not in t:
            t += '.0'
        return t + 'f'
    chunk = ', '.join(lit(v) for v in values[i:i+4])
    lines.append('    ' + chunk + ',')
body = '\n'.join(lines)
out = f'''// Generated by tools/make-sine-table.py. Do not edit by hand.
//
// One period of sine, {N}+1 entries so the interpolation can read i+1 without
// wrapping. Committed as literals rather than computed at startup for the same reason
// the sfxr reference carries its own PRNG: three toolchains' libm produce three
// slightly different sines, and the feedback path amplifies a one-ULP disagreement to
// full scale within a tenth of a second. A table of committed constants is the same
// wave on every machine, and lerp between entries is plain IEEE multiply-add, which
// every target rounds identically.
#pragma once

namespace soundgraph {{
namespace dsp {{

inline constexpr int kSineTableSize = {N};

inline constexpr float kSineTable[{N + 1}] = {{
{body}
}};

}}  // namespace dsp
}}  // namespace soundgraph
'''
io.open('dsp-core/src/sine_table.h', 'w', newline='\n').write(out)
print('sine_table.h regenerated')
